Logs now include timestamps

diff --git a/loggers b/loggers
--- a/loggers
+++ b/loggers
@@ -1,21 +1,23 @@
 #!/bin/bash
 set -euo pipefail
 
-# TODO: add timestamps
+# colors
+reset=$'\e[m'
+green=$'\e[0;32m'
+red=$'\e[0;31m'
+blue=$'\e[0;34m'
+
+# date format string
+_iso8601_fmt="%Y-%m-%dT%H:%M:%S%z"
+
 function log_info() {
-    local green=$'\e[0;32m'
-    local reset=$'\e[m'
-    echo "${green}[info]${reset} $1"
+    echo "${green}[$(date +"${_iso8601_fmt}")][info]${reset} $1"
 }
 
 function log_error() {
-    local red=$'\e[0;31m'
-    local reset=$'\e[m'
-    echo "${red}[error]${reset} $1" 1>&2
+    echo "${red}[$(date +"${_iso8601_fmt}")][error]${reset} $1" 1>&2
 }
 
 function log_debug() {
-    local blue=$'\e[0;34m'
-    local reset=$'\e[m'
-    echo "${blue}[debug]${reset} $1"
+    echo "${blue}[$(date +"${_iso8601_fmt}")][debug]${reset} $1"
 }
